model:
  name: resnet18
  params: {}

dataset:
  name: imagenette
  train_test_split: 0.8
  batch_size: 32
  transforms:
    torchvision.transforms.Resize:
      size: [224, 224]
    torchvision.transforms.ToTensor: {}
    torchvision.transforms.Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  truncate: 0.05
  data_folder: ./data

training:
  snapshot_path: snapshot.pth
  save_every: 1
  n_epochs: 10
  loss:
    name: torch.nn.CrossEntropyLoss
    params: {}

  optimizer:
    name: torch.optim.Adam
    params:
      lr: 0.001
      weight_decay: 0.0001


defaults:
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

hydra:
  output_subdir: null
